"""documenttemplatingfieldsschema

Revision ID: 90668cda208b
Revises: cbb5ea3a7323
Create Date: 2025-04-09 06:28:18.363038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90668cda208b'
down_revision: Union[str, None] = 'cbb5ea3a7323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_templates', sa.Column('fields_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('document_templates', 'schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_templates', sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('document_templates', 'fields_schema')
    # ### end Alembic commands ###
