"""documenttemplatingname

Revision ID: cbb5ea3a7323
Revises: 2bdc4649b9ed
Create Date: 2025-04-09 05:58:52.994866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb5ea3a7323'
down_revision: Union[str, None] = '2bdc4649b9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_templates', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'document_templates', 'template_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_templates', type_='foreignkey')
    op.drop_column('document_templates', 'category_id')
    # ### end Alembic commands ###
